### ISSUE TITLE
Is it possible to invoke C# methods from javasript with Javascript.NodeJS?

### ISSUE THREAD

**Issue by smilovich** [JeringTech/Javascript.NodeJS#104]
I didn't find this ability in documentation. Are you planning to add ability invoke C# methods from node.js application? 
It would be great to have it, because edje.js is not maintainable for a long time and your project can replace it in future.

**Comment by JeremyTCD** [comment]
Unfortunately it isn't possible. Agree that it would be useful, but it's beyond what we need from the library at the moment (for our own applications). Was going to recommend https://github.com/agracio/edge-js but noticed you have an issue there already.  

Perhaps you could build separate applications (a node.js application and a .Net application) and communicate between them using plain HTTP or grpc.
