### ISSUE TITLE
Error installing latest stable version

### ISSUE THREAD

**Issue by markzolotoy** [JeringTech/Javascript.NodeJS#107]
I am trying adding a package version 5.4.4 and getting this:
Failed to add reference to 'System.Memory'.
Error HRESULT E_FAIL has been returned from a call to a COM component.

as a result the package is not installed. Any idea?

**Comment by markzolotoy** [comment]
If I use latest beta the error is:
Failed to add reference to 'System.ValueTuple'.
Error HRESULT E_FAIL has been returned from a call to a COM component.

**Comment by JeremyTCD** [comment]
Hi again, I Googled the error and found this thread: [Add a reference raise error: Error HRESULT E_FAIL has been returned from a call to a COM component](https://developercommunity.visualstudio.com/t/add-a-reference-raise-error-error-hresult-e-fail-h/260196).  

Let me know if the solutions there work.  

Also do other libraries cause the same error?

**Comment by markzolotoy** [comment]
The problem was happening when I was selecting the Nuget package first and
then selecting a project to add the package to.
I tried then adding a package by going into References of the target
project and then selecting the package.
That worked for me.

**Comment by JeremyTCD** [comment]
Ah okay. Glad the issue's been resolved. Feel free to open another issue if you have more questions!
