### ISSUE TITLE
Error message has newline (\n) character in it?

### ISSUE THREAD

**Issue by princefishthrower** [JeringTech/Javascript.NodeJS#109]
Let's say in the `module.exports` that I expose to .NET I do this:

```javascript
catch (error) {
    throw "TEST"
}
```

Back in .NET, the exception is caught just fine as expected (I'm wrapping a try / catch around `nodeJSService.InvokeFromFileAsync`), but if I examine `exception.Message`, I don't get `TEST` as expected, I get `TEST\n`. 

In .NET this is trivial to remove, but it shouldn't be there in the first place, right?  I figured I would report this unexpected behavior here, and also ask if I am doing something wrong to cause this newline character to be in my exception message?

Anyway, super cool package - it's helping me call some external TypeScript / JavaScript code that would be near impossible to port into the C# language!

**Comment by JeremyTCD** [comment]
Yeap you're right, the `\n` shouldn't be there. The exception message is composed here:

https://github.com/JeringTech/Javascript.NodeJS/blob/7298989a7f0897126497e37c1036bb6e5e89070f/src/NodeJS/NodeJSServiceImplementations/InvocationData/InvocationException.cs#L33

It should only add the `\n` if there is a stack trace. The entire line of code isn't great in general, will fix it some time this week.  

I'm glad you like the package :smiley:, and I appreciate your reporting the mistake! If you come across any other issues - however trivial seeming - feel free to report them.

**Comment by princefishthrower** [comment]
@JeremyTCD - thanks for looking into this so quickly! 

I wonder if I could also get your opinions on this package vs calling the Node.js code over a traditional REST API (ex. exposing it with express, then using .NET's HTTPClient to call it)- my thoughts were that this package cuts out a lot of intermediate steps that would be taken if going that HTTP way, so I'm hoping it would be 'faster', but I can't say for sure since I haven't looked into the architecture behind this package. 😄  

I realize at least as much that the Node.js code itself is cached after the first call, which has to make some speed savings, but otherwise haven't looked to compare the speed vs calling it over an API or other protocol (a socket, perhaps). Do you have any thoughts on this?

I'll definitely report if I find any other issues, so far it's working fine!

**Comment by JeremyTCD** [comment]
Just fixed the exception message and published [6.0.1](https://www.nuget.org/packages/Jering.Javascript.NodeJS/6.0.1) 😃!

I haven't benchmarked the library against a REST API, I think you might be right about it being faster though. This library does avoid routing, misc middleware etc, and it doesn't add anything on top.

Under-the-hood, it sends your cache identifier and remote procedure arguments straight to NodeJS's `http.Server` (which express is built on top of). The server retrieves your procedure from a simple map, invokes it and returns the result. The whole process is fairly lightweight.  

With regard to alternative protocols, [Microsoft.AspNetCore.NodeServices](https://github.com/aspnet/JavaScriptServices/tree/master/src/Microsoft.AspNetCore.NodeServices) implemented invocations over sockets. It's performance was similar to `HttpClient`:

> Now when you run your application, it will use the socket-based hosting and transport mechanism. In the past, the socket transport was faster than HTTP, but since .NET Core 1.1 improved the performance of HttpClient there isn't really any speed difference any more, so there's no longer any significant advantage to using Microsoft.AspNetCore.NodeServices.Sockets

I'd be happy to merge implementations using alternative transports, but am not planning to write any.

**Comment by princefishthrower** [comment]
@JeremyTCD - awesome, thanks for this. Thanks for the info as well - it's starting to sound like any concerns in terms of transport speeds I have will likely be negligible compared to what I am doing with my Node code (some abstract syntax tree manipulation with the TypeScript Compiler API - not exactly the fastest thing in the world!)
