### ISSUE TITLE
PhysicalFileProvider.Root and file not found issues in production build

### ISSUE THREAD

**Issue by princefishthrower** [JeringTech/Javascript.NodeJS#112]
My Node.js project lives under a `Microservices` folder within my .NET project. In development, doing something like this works fine:

```csharp
services.AddNodeJS();
var physicalFileProvider = new PhysicalFileProvider(Directory.GetCurrentDirectory());
var projectPath = Path.Combine(physicalFileProvider.Root, "Microservices", "my-specific-node-js-microservice-folder");
services.Configure<NodeJSProcessOptions>(options => options.ProjectPath = projectPath);
```

and then, (since I use TypeScript and produce `.js` file artifacts - this is already done during the build stage, and I am sure that the file exists), the actual file to call is`./dist/index.js`:

```csharp
return await nodeJSService.InvokeFromFileAsync<Generated>("./dist/index.js", args: new[] { generatorOptions.StateCode });
```

I've tried a variety of file paths now for my production build, even hardcoding the relative file path from the root of my machine to `index.js`. All various ways of specifying the path work fine in development, but none work on my production server. I always get:

```
[2] Refer to the InnerException for further details.
        ---> System.ComponentModel.Win32Exception (2): No such file or directory
          at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentia>
          at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
          at System.Diagnostics.Process.Start()
          at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
          at Jering.Javascript.NodeJS.NodeJSProcessFactory.CreateProcess(ProcessStartInfo startInfo)
          --- End of inner exception stack trace ---
          at Jering.Javascript.NodeJS.NodeJSProcessFactory.CreateProcess(ProcessStartInfo startInfo)
          at Jering.Javascript.NodeJS.NodeJSProcessFactory.Create(String serverScript)
          at Jering.Javascript.NodeJS.OutOfProcessNodeJSService.CreateAndSetUpProcess(EventWaitHandle waitHandle)
          at Jering.Javascript.NodeJS.OutOfProcessNodeJSService.ConnectIfNotConnected()
```

No matter what path I specify, the package complains that it cannot find my `index.js` file. What's going wrong here? This may be unrelated to this package, but I've used `PhysicalFileProvider` and the `Root` value with many other projects and it has worked as expected. Is there some other setting I need to set other than `options.ProjectPath`? If it's helpful, my production server is an Ubuntu 21.04 instance.

I saw in [this issue](https://github.com/JeringTech/Javascript.NodeJS/issues/111) that one can use `AppDomain.CurrentDomain.BaseDirectory` instead of `physicalFileProvider.Root` as the root folder, but I don't deploy my Node.js project as an assembly - as I mentioned, it sits in its own `Microservices` folder in the .NET project root.

Any thoughts or ideas of what could be missing here?

**Comment by JeremyTCD** [comment]
```
System.ComponentModel.Win32Exception (2): No such file or directory
          at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentia>
```

Hey there, `Win32Exception` is thrown when the application can't find Node.js. Could you double check that it's installed and added to the path variable?

**Comment by princefishthrower** [comment]
Ah thanks for this, that hint was misleading and I was overthinking it. However, on .NETs part I _had_ set the PATH variable (I am using nvm, so I set the PATH variable to `/root/.nvm/versions/node/v14.17.0/bin/`) . After reading [this issue](https://github.com/aspnet/JavaScriptServices/issues/1265), it seems like the Node.js binary has to be under the production folder? The whole thing works fine after I copied the node binary to that production folder... perhaps there is some setting within .NET where the binary can't be outside of the project folder? Strange... Anyway, thanks for guiding me in the right direction!

**Comment by ganesh328916** [comment]
> 

How do I identify the production folder in azure app service @princefishthrower ?

**Comment by ganesh328916** [comment]
> ```
> System.ComponentModel.Win32Exception (2): No such file or directory
>           at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentia>
> ```
> 
> Hey there, `Win32Exception` is thrown when the application can't find Node.js. Could you double check that it's installed and added to the path variable?

@JeremyTCD , Eventhough after adding the PATH variable, I'm still facing the same issue
