### ISSUE TITLE
Jering.Javascript.NodeJS.ConnectionException on Azure App Service

### ISSUE THREAD

**Issue by heinzmuller** [JeringTech/Javascript.NodeJS#115]
Hi! I am currently experiencing an error when deploying an app to a Linux App Service running .NET 5.

I have checked to make sure `node` is available for the app via kudu and it should be in the PATH printed in the exception.

```
---> Jering.Javascript.NodeJS.ConnectionException: Failed to connect to NodeJS. Refer to the inner exception for details.
--
  | ---> System.InvalidOperationException: Failed to start Node process. To resolve this:
  |  
  | [1] Ensure that NodeJS is installed and can be found in one of the PATH directories. The current PATH enviroment variable is: /opt/dotnetcore-tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/site/wwwroot. Make sure that the Node executable is in one of those directories, or update your PATH.
  |  
  | [2] Refer to the InnerException for further details.
  | ---> System.ComponentModel.Win32Exception (2): No such file or directory
  | at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32&amp; stdinFd, Int32&amp; stdoutFd, Int32&amp; stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
  | at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
  | at System.Diagnostics.Process.Start()
  | at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
  | at Jering.Javascript.NodeJS.NodeJSProcessFactory.CreateProcess(ProcessStartInfo startInfo)
  | --- End of inner exception stack trace ---
  | at Jering.Javascript.NodeJS.NodeJSProcessFactory.CreateProcess(ProcessStartInfo startInfo)
  | at Jering.Javascript.NodeJS.NodeJSProcessFactory.Create(String serverScript)
  | at Jering.Javascript.NodeJS.OutOfProcessNodeJSService.CreateAndSetUpProcess(EventWaitHandle waitHandle)
  | at Jering.Javascript.NodeJS.OutOfProcessNodeJSService.ConnectIfNotConnected()
  | --- End of inner exception stack trace ---
  | at Jering.Javascript.NodeJS.OutOfProcessNodeJSService.ConnectIfNotConnected()
  | at Jering.Javascript.NodeJS.OutOfProcessNodeJSService.TryInvokeCoreAsync[T](InvocationRequest invocationRequest, CancellationToken cancellationToken)
  | at Jering.Javascript.NodeJS.OutOfProcessNodeJSService.InvokeFromStringAsync[T](String moduleString, String cacheIdentifier, String exportName, Object[] args, CancellationToken cancellationToken)
```

Kudu
```
$ whereis node
node: /usr/local/bin/node
$ node -v
v10.22.0
```

**Comment by JeremyTCD** [comment]
Hey there,

I'm not familiar with Azure App Service, but from the error, I'm pretty certain that Node isn't on the path of your application instance. More probably it is not installed.  

Wrt to Kudu, I'm not familiar with it, but considering that `node -v` runs, your Kudu instance is probably separate from your application instance. Kudu looks like a CI/CD service, so this is expected.  

I'd suggest reading up on App Service. You might need a [custom container](https://docs.microsoft.com/en-us/azure/app-service/quickstart-custom-container?pivots=container-linux) if there is no built-in container for .Net + Node.js.

**Comment by pynej** [comment]
You may need to explicitly force a real version in your Configuration on the App Service:
WEBSITE_NODE_DEFAULT_VERSION=14.15.1

**Comment by pynej** [comment]
It defaults to a 0.X that doesn't work right. Also the startup is pretty slow and I'm not sure why. (running node job in Kudu/server ~12s, running the same job via INodeJSService takes ~40s for the first request. Then it's all loaded and is supper fast.

**Comment by JeremyTCD** [comment]
Closing for now. Thanks @pynej for the tips. If you're still having trouble with startup time feel free to open another issue.

**Comment by ganesh328916** [comment]
> It defaults to a 0.X that doesn't work right. Also the startup is pretty slow and I'm not sure why. (running node job in Kudu/server ~12s, running the same job via INodeJSService takes ~40s for the first request. Then it's all loaded and is supper fast.

It doesn't works for me any other solution?

**Comment by heinzmuller** [comment]
The issue is that the .NET Docker containers that Azure use for Web Apps does not contain a node instance by default, meaning you will have to add it to the app manually. We are almost exclusively deploying Optimizely CMS apps and they have added support for defining a node version to add the image, maybe there is some clues there on how to do it without Optimizely? :)

https://support.optimizely.com/hc/en-us/articles/7863447798157-Configure-NodeJs-on-DXP-Linux-NetCore-
