### ISSUE TITLE
Error Json Value cannot be converted to byte[]

### ISSUE THREAD

**Issue by aboah** [JeringTech/Javascript.NodeJS#118]
I tried using your library to **execute QrCode by Nodejs**. I get the error Json Value cannot be converted to byte[]. 
I beleieve part of the problem is the use of System.Text.Json instead of Newtonsoft.Json.
How can I change the deserialization process.

if System.Text.Json is not the issue how can we use your library to consume qr-image node module?

**Comment by JeremyTCD** [comment]
Sorry for the late reply. 

`System.Text.Json` does behave atypically with `byte[]`s. You have a couple of options here:

1. Return a base64 string:
    ```cs
    using Jering.Javascript.NodeJS;
    using Xunit;
    
    namespace Temp
    {
        class Program
        {
            static async Task Main(string[] _)
            {
                // Returns byte array as base64 string
                string dummyModule = @"module.exports = (callback) => {
        callback(null, { ""DummyByteArray"": Buffer.from([0, 1, 2]).toString('base64') });
    }";
    
                // Executes dummy module
                DummyClass? result = await StaticNodeJSService.InvokeFromStringAsync<DummyClass>(dummyModule).ConfigureAwait(false);
    
                // Validate
                Assert.Equal(new byte[] { 0, 1, 2 }, result!.DummyByteArray);
            }
        }
    
        public class DummyClass
        {
            public byte[]? DummyByteArray { get; set;  }
        }
    }
    ```
    This is how `System.Text.Json` works by default - it expects a base64 string when you deserialize to `byte[]`.

2. Write a custom `IJsonService`. Find detailed instructions [here](https://github.com/JeringTech/Javascript.NodeJS/issues/79#issuecomment-748464845). With this approach you can use any JSON library you like. You can also just add a custom `byte[]` converter for `System.Text.Json`.

**Comment by JeremyTCD** [comment]
Closing since resolved, feel free to open another issue if you have more questions.
