### ISSUE TITLE
Security concern: Is the node process isolated from the file system or network?

### ISSUE THREAD

**Issue by panospd** [JeringTech/Javascript.NodeJS#120]
In use cases where JavaScript come comes from front end and we don't know exactly what that code is doing would be nice if the node process would be isolated without the ability to access the file system or network. 

Deno does the above by default. World it be difficult to support deno along with node and be able to execute JavaScript using a deno subprocess?

**Comment by JeremyTCD** [comment]
Hi, have you considered [vm2](https://github.com/patriksimek/vm2) for node?  

I'm not familiar with deno, but if vm2 is insufficient I'm open to merging support for deno.

**Comment by ulieckstein** [comment]
how can i use vm2 in combination with nodejs? does it need to be installed globally on the server?

**Comment by JeremyTCD** [comment]
vm2 is a Javascript library: [vm2 on NPM](https://www.npmjs.com/package/vm2). Basically it lets you "eval" untrusted code by hiding sensitive Node.js APIs.

Example from their NPM page:

```js
const vm = require('vm');
vm.runInNewContext('this.constructor.constructor("return process")().exit()');
console.log('Never gets executed.');
```

**Comment by JeremyTCD** [comment]
Closing for now, feel free to open another issue if you have any other questions.
