### ISSUE TITLE
Add a method to manually invalidate the cached script

### ISSUE THREAD

**Issue by highfield** [JeringTech/Javascript.NodeJS#121]
In addition to the file-watcher, why not adding a method to manually force the script reload from file?

The `FileSystemWatcher` is rather expensive, and sometimes (like my case) the file change seldomly happens. So, I we expose the `MoveToNewProcess` method to the interface, that would be publicly callable, and the game should be over.

Is that feasible?

**Comment by JeremyTCD** [comment]
Good idea and definitely feasible. `MoveToNewProcess` should be safe to expose, will look at this tomorrow.

**Comment by JeremyTCD** [comment]
Exposed the method in [6.1.0](https://www.nuget.org/packages/Jering.Javascript.NodeJS/6.1.0), let me know if you have any issues with it.

**Comment by dingbat1** [comment]
I'm doing some long running scripts and using the .NET FileSystemWatcher to handle reloads. This allows a bit more control from the server side, and I have some "stop" methods I await before triggering a new load.
To cache-bust I am calling the StaticNodeJSService.MoveToNewProcess() successfully.
However, I'm wondering how that may effect multiple scripts running. Are they invoked on their own process?

**Comment by JeremyTCD** [comment]
@dingbat1 

Apologies for the slow response. `MoveToNewProcess` is safe: processes are only killed when their invocations complete (so long as [`OutOfProcessNodeJSServiceOptions.GracefulProcessShutdown`](https://github.com/JeringTech/Javascript.NodeJS#outofprocessnodejsserviceoptionsgracefulprocessshutdown) is `true`).

https://github.com/JeringTech/Javascript.NodeJS/blob/0517756a04fb08df365baa48492a15c23ae9a045/src/NodeJS/NodeJSServiceImplementations/OutOfProcess/OutOfProcessNodeJSService.cs#L628-L649

**Comment by dingbat1** [comment]
Thanks for the additional information. I have the library working well now - thank you for all your work.

In my case, I had a lot of problems with the interactions between processes when updating scripts.

- I have a long running script that exposes "invoke" and "destroy" methods.
- The purpose of the "destroy" is to allow the script to close any connections and do some cleanup. It would also be OK if the "destroy" is not called, so long as the NodeJS process recycled.
- When using the NodeJS watcher, an updated script is not automatically stopped and restarted.
- Detecting the update from the .NET FileSystemWatcher allows for calling the script's "destroy" method, and then calling the MoveToNewProcess(). However, this had a lot of concurrency issues and it was too hard to control the order of things.
- When using .NET FileSystemWatcher only, I can control the "destroy" and new "invoke" on a script update. However, NodeJS still caches the old script.

My ultimate solution was to pass the script in as String, then on update call the "destroy" method from the cache. This uses only the .NET FSW to do updates.

It is working well now, but there may be some scope for a little finer control over the recycling process when a new file is detected. For short/function scripts it's probably never an issue. But in my application I plan some scripts will run forever (or until faulted).

Hope the feedback helps and I was pleased to be able to get the library 100% working through the above solution. Thanks again!
