### ISSUE TITLE
Update preprocessor directives to use NET5_0_OR_GREATER to support .net 6

### ISSUE THREAD

**Issue by samcic** [JeringTech/Javascript.NodeJS#127]
In various parts of the codebase, e.g. `HttpNodeJSService.cs`, we see preprocessor directives like

```
#if NETCOREAPP3_1 || NET5_0
...
#endif
```

Now that .net 6 is out, would the following make more sense?

```
#if NETCOREAPP3_1 || NET5_0_OR_GREATER
...
#endif
```

From what I can tell, using this library in a .net 6 app doesn't allow for the use of HTTP 2.0, for example.

Happy to contribute a PR if it's easier to get this change in, just let me know!

**Comment by JeremyTCD** [comment]
Hey yeah makes sense. Would appreciate a PR!
