### ISSUE TITLE
I want to subscribe to events

### ISSUE THREAD

**Issue by hbdbim** [JeringTech/Javascript.NodeJS#130]
First congratulations, lib fantastica.

I wanted to know if there is a way to subscribe to events.
something like that
https://github.com/tjanczuk/edge#how-to-handle-nodejs-events-in-net

I want to consume this lib
https://github.com/adiwajshing/Baileys
uses many events.

**Comment by JeremyTCD** [comment]
Hey thanks! 

This library doesn't support subscribing to JS events. In general it doesn't have an official way to send data from JS to C#.  

I don't have the bandwidth to add such support but am open to pull requests.  

As for workarounds:

- The JS process's stdout is piped to the .NET logging framework. You could `console.log` from JS and read the output from a custom [logging provider](https://docs.microsoft.com/en-us/dotnet/core/extensions/custom-logging-provider).

- If your C# application is a web application you could send loopback HTTP requests to it from the JS process. 

- If it is not a web application you could start Kestrel and send loopback requests.

**Comment by hbdbim** [comment]
Thanks for the answer.
I'm trying to implement the console option but `console.log` is not writing anything to the console.

Windows environment, do you have any tips?

**Comment by hbdbim** [comment]
found an example.
https://github.com/JeringTech/Javascript.NodeJS/issues/129

I think it will work perfect.

**Comment by dingbat1** [comment]
If you want to communicate between JS & ASP.NET (Core) I can recommend a SignalR implementation. It doesn't need much code (and there are a lot of examples) to get events/methods moving between front-end and back-end in realtime. Came here looking for an event on the NodeJS file watcher.

**Comment by JeremyTCD** [comment]
@dingbat1 again, sorry about responding slowly to your comments. Glad you got things working in the other comment. Agree on SignalR - am using it in a private project and the API is great. Also agree that two-way communication would be a significant improvement for this library. As ever, the main blocker is development time. Any interest in having a go?
