### ISSUE TITLE
JS is not backwards compatible

### ISSUE THREAD

**Issue by johnrom** [JeringTech/Javascript.NodeJS#131]
The original AspNetCore NodeJS service was capable of using commonjs to run JS code:

```js
module.exports = {
  default: (callback) => {}
};
```

This one, however, requires that the callback function be returned to `module.exports`. 

```js
module.exports = (callback) => {};
```

Documenting a migration path would be helpful. In Webpack this behavior can be configured like this:

```js
module.exports = {
  // etc
  output: {
    library: 'commonjs2',
    libraryExports: 'default',
  }
};
```

This simply assigns `modules['default']` instead of `modules` to `module.exports`.

**Comment by JeremyTCD** [comment]
Hey, apologies for the slow reply.

You can assign an object to `module.exports`:

```cs
static async Task Main(string[] _)
{
    string module = @"module.exports = {
    default: (callback) => callback(null, ""default invoked"")
}";
    string? result = await StaticNodeJSService.InvokeFromStringAsync<string>(module, exportName: "default");

    Console.WriteLine(result);
}
```

Documentation for this feature can be found here: [Invoking Javascript](https://github.com/JeringTech/Javascript.NodeJS#invoking-javascript).

Is that what you're looking for?

**Comment by johnrom** [comment]
That makes sense, and is probably more flexible overall. In the original AspNetCore, using a null export name would use the default export.
