### ISSUE TITLE
JsCompilationException on spawn identifier

### ISSUE THREAD

**Issue by soroshsabz** [JeringTech/Javascript.NodeJS#139]
ITNOA

Hi

I have a GitHub project https://github.com/soroshsabz/visualstudio-ansible and in Ansible.VisualStudio.LanguagerServer vs project, I have SpawnServer.js file that content like below

```js
const { spawn } = require("child_process");

spawn("npx", ["ansible-language-server"].concat(process.argv[2]), { stdio: 'inherit' });
```

When I want to run this script from C# code I got JsCompilationException withe below details

```
Exception thrown: 'JavaScriptEngineSwitcher.Core.JsCompilationException' in JavaScriptEngineSwitcher.Node.dll
An unhandled exception of type 'JavaScriptEngineSwitcher.Core.JsCompilationException' occurred in JavaScriptEngineSwitcher.Node.dll
SyntaxError: Identifier 'spawn' has already been declared
   at SpawnServer.js:1:1 -> // ITNOA
```

My loading code like below

```csharp
using JavaScriptEngineSwitcher.Core;
using JavaScriptEngineSwitcher.Jurassic;
using JavaScriptEngineSwitcher.Node;
using System;

namespace Ansible.VisualStudio.LanguageServer
{
    public class Loader
    {
        public Loader()
        {
            IJsEngine engine = new NodeJsEngine();
            engine.ExecuteFile("SpawnServer.js");
        }
    }
}
```

**Where is my wrong?**

if you want to see my code in GitHub you can see [language-server branch](https://github.com/soroshsabz/visualstudio-ansible/tree/features/4-support-ansible-language-server)

thanks

**Comment by Taritsyn** [comment]
Hello!

To use the `require` function, you need to assign the `UseBuiltinLibrary` property a value equal to `true` (see the [documentation for the JavaScriptEngineSwitcher.Node module](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/Node)):

```csharp
IJsEngine engine = new NodeJsEngine(new NodeSettings { UseBuiltinLibrary = true });
```

**Comment by Taritsyn** [comment]
In general, to execute code oriented on working with Node.js is better to use the [Jering.Javascript.NodeJS](https://github.com/JeringTech/Javascript.NodeJS) library directly.

**Comment by soroshsabz** [comment]
Very thank you, if you want you can answer this question on [SO](https://stackoverflow.com/q/72996212/1539100) to get reputation.
