### ISSUE TITLE
Apparent hang using the cached code

### ISSUE THREAD

**Issue by highfield** [JeringTech/Javascript.NodeJS#140]
Very strange behavior. Still couldn't figure out what's up.
Consider this code, which is part of a very basic Asp Net 6 app:

    public class MyClass
    {
        private const string CacheId = "example-Module";

        public MyClass(
            INodeJSService nodeJSService
            )
        {
            this._nodeJSService = nodeJSService;
        }

        private readonly INodeJSService _nodeJSService;
        private readonly SemaphoreSlim _semaf = new(1, 1);

        private async Task EnsureStartedAsync(
            CancellationToken token
            )
        {
            const string funcName = "start_test";
            int num = 123;

            (bool success, int result) = await this._nodeJSService.TryInvokeFromCacheAsync<int>(
                CacheId,
                funcName,
                new object[] { num },
                token
                );

            if (success == false)
            {
                //init cache
                string moduleString = @"
    module.exports = {
        start_test: num => num * 7,
        calc: (callback, message) => callback(null, { message: message }),
    };
    ";

                // *** the flow halts here ***
                result = await this._nodeJSService.InvokeFromStringAsync<int>(
                    moduleString,
                    CacheId,
                    funcName,
                    new object[] { num },
                    token
                    );
            }

            if (result != num * 7)
            {
                throw new Exception();
            }
        }

        public async Task CalcAsync(
            CancellationToken token
            )
        {
            await this._semaf.WaitAsync(token);

            try
            {
                await this.EnsureStartedAsync(token);

                // Send the module string to NodeJS where it's compiled, invoked and cached.
                var (success, result) = await this._nodeJSService.TryInvokeFromCacheAsync<Result>(
                    CacheId,
                    "calc",
                    args: new[] { "success" },
                    cancellationToken: token
                    );

                Console.WriteLine($"success={success}; result={result?.Message}");
            }
            finally
            {
                this._semaf.Release();
            }
        }

        private class Result
        {
            public string Message { get; set; } = string.Empty;
        }

    }

When the program runs, it reaches the `InvokeFromStringAsync` to load the module source, then halts. Actually, it waits for about one minute, which seems like an HTTP timeout. However, no exception, nor any other hint comes to rescue.
That's very strange, because by using this version inside the `EnsureStartedAsync` method, everything is going fine:

            // *** this works ***
            var (success, result) = await this._nodeJSService.TryInvokeFromCacheAsync<Result>(
                CacheId,
                args: new object[] { "success" },
                cancellationToken: token
                );

            if (success == false)
            {
                //init cache
                string moduleString = "module.exports = (callback, message) => callback(null, { message: message })";

                result = await this._nodeJSService.InvokeFromStringAsync<Result>(
                    moduleString,
                    CacheId,
                    args: new object[] { "success" },
                    cancellationToken: token
                    );

                success = true;
            }
            Debug.Assert(success, result?.Message);

Finally, below there is a slightly modified version of the above one. This does NOT work:

            // *** this does NOT work ***
            var (success, result) = await this._nodeJSService.TryInvokeFromCacheAsync<Result>(
                CacheId,
                args: new object[] { "success" },
                cancellationToken: token
                );

            if (success == false)
            {
                //init cache
                string moduleString = @"
    module.exports = {
        func: (callback, message) => callback(null, { message: message })
    }
    ";

                result = await this._nodeJSService.InvokeFromStringAsync<Result>(
                    moduleString,
                    CacheId,
                    "func",
                    args: new object[] { "success" },
                    cancellationToken: token
                    );

                success = true;
            }
            Debug.Assert(success, result?.Message);

Any idea?
Thank you in advance.

**Comment by JeremyTCD** [comment]
For the first issue, `start_test` needs a `callback` parameter:

```cs
private async Task EnsureStartedAsync(
    // ...

    string moduleString = @"
module.exports = {
start_test: (callback, num) => callback(null, num * 7),
calc: (callback, message) => callback(null, { message: message }),
};
";

    // ...
}
```

The last block of code works fine for me (made some changes so it can run in a console app):

```cs
internal class Program
{
    private const string CacheId = "example-Module";

    static async Task Main(string[] args)
    {
        var (success, result) = await StaticNodeJSService.TryInvokeFromCacheAsync<Result>(
            CacheId,
            args: new object[] { "success" },
            cancellationToken: CancellationToken.None
            );

        if (success == false)
        {
            //init cache
            string moduleString = @"
module.exports = {
func: (callback, message) => callback(null, { message: message })
}
";

            result = await StaticNodeJSService.InvokeFromStringAsync<Result>(
                moduleString,
                CacheId,
                "func",
                args: new object[] { "success" },
                cancellationToken: CancellationToken.None
                );

            success = true;
        }

        Assert.True(success);
        Console.WriteLine(result?.Message); // Prints as expected
    }

    private class Result
    {
        public string Message { get; set; }
    }
}
```
What exception are you getting from it?

On an aside, I'd recommend using the [`InvokeFromString` overload that takes a module factory](https://github.com/JeringTech/Javascript.NodeJS#inodejsserviceinvokefromstringasynctfuncstring-string-string-object-cancellationtoken). It handles the cache check for you: [docs](https://github.com/JeringTech/Javascript.NodeJS#invoking-javascript-in-string-form).

**Comment by highfield** [comment]
Oh, well...thank you for the quick response!
I accept that the signature must be callback-like, but at this point I wonder how this other script is working, then?
This is what a small Typescript function produced and it works with no problems. The only difference, if you want, is that it runs by the Static API instead the DI one.
```
async function create(input) {
    return new Promise(resolve => {
        const { fromDT, quantum, } = input;
        const fromDTValue = Date.parse(fromDT);
        const count = 10;
        const samples = [];
        for (let i = 0; i < count; i++) {
            const s = {
                timestamp: new Date(fromDTValue + 86400 * i).toISOString(),
                value: i * quantum,
            };
            samples.push(s);
        }
        resolve({
            count,
            samples,
        });
    });
}
module.exports = {
    create,
};
```

For the other snippet, I get this exception from the console log:
```
warn: Jering.Javascript.NodeJS.HttpNodeJSService[0]
      An invocation attempt failed. Retries using existing process remaining: 0.
      Exception:
        Jering.Javascript.NodeJS.InvocationException: The module "example-Module..." does not export a function.
         at Jering.Javascript.NodeJS.HttpNodeJSService.TryInvokeAsync[T](InvocationRequest invocationRequest, CancellationToken cancellationToken)
         at Jering.Javascript.NodeJS.OutOfProcessNodeJSService.TryInvokeCoreAsync[T](InvocationRequest invocationRequest, CancellationToken cancellationToken)
```

**Comment by highfield** [comment]
Ummm...nope. Neither with the callback works. It gives the same exception as above: 

> The module "example-Module..." does not export a function.

**Comment by highfield** [comment]
> Ummm...nope. Neither with the callback works. It gives the same exception as above:
> 
> > The module "example-Module..." does not export a function.

False alarm! It was me, likely because I should stop working after a certain time!
The callback way works, while the Promise one does not. Anything changed since around a year?
To me, the problem is over. Thanks once again.

**Comment by JeremyTCD** [comment]
Haha okay, glad you got it working!

As for promises, this works for me:

```cs
namespace Temp
{
    internal class Program
    {
        private const string CacheId = "example-Module";

        static async Task Main(string[] args)
        {
            var (success, result) = await StaticNodeJSService.TryInvokeFromCacheAsync<Result>(
                CacheId,
                args: new object[] { "success" },
                cancellationToken: CancellationToken.None
                );

            if (success == false)
            {
                string moduleString = @"
async function echo(message) { 
    return new Promise(resolve => resolve({ Message: message })); 
}

module.exports = {
    func: echo
}
";

                result = await StaticNodeJSService.InvokeFromStringAsync<Result>(
                    moduleString,
                    CacheId,
                    "func",
                    args: new object[] { "success" },
                    cancellationToken: CancellationToken.None
                    );

                success = true;
            }

            Assert.True(success);
            Console.WriteLine(result?.Message);
        }

        private class Result
        {
            public string Message { get; set; }
        }
    }
}
```
From your snippet this might be the issue:
```
// ...
module.exports = {
    func: create // Must be assigned to a property
};
```
