### ISSUE TITLE
Get exception "Failed to connect to NodeJS" in docker paslock/dotnet-nodejs:dotnet5.0-nodejs16

### ISSUE THREAD

**Issue by datanglibai** [JeringTech/Javascript.NodeJS#142]
I've tried running my program based on docker image  paslock/dotnet-nodejs:dotnet5.0-nodejs16
and Get exception "Failed to connect to NodeJS" 
Not sure what is missing in the environment without detailed information.
I checked image, node is installed.
Anyone tried the library in .net5 docker image?

**Comment by JeremyTCD** [comment]
Hello, what is the `ConnectionException`'s inner exception?

**Comment by datanglibai** [comment]
i think i can close the issue since it is caused by a false deployment. sorry for the noise.
