### ISSUE TITLE
Node startup fails on Azure App Service

### ISSUE THREAD

**Issue by aKzenT** [JeringTech/Javascript.NodeJS#145]
This is related to https://github.com/JeringTech/Javascript.NodeJS/issues/143 . Basically when we had an outage last week we encountered the long connection timeout but we did not understand why the connection failed in the first place. After some investigation the error occured while changing the application insights configuration on the app service. It seems that changing the application insights configuration activated the following configuration setting without our knowledge:

`XDT_MicrosoftApplicationInsights_NodeJS = 1`

This influences Node JS processes started on the app service host causing them to create an additional output at the beginning:

```
AppInsightsAgent: Successfully loaded ETW
AppInsightsAgent ETWLogger Application Insights was started with setupString: InstrumentationKey=XXX;IngestionEndpoint=https://westeurope-0.in.applicationinsights.azure.com/;LiveEndpoint=https://westeurope.livediagnostics.monitor.azure.com/
[Jering.Javascript.NodeJS: HttpVersion - HTTP/2.0 Listening on IP - 127.0.0.1 Port - 52511]
```

Notice the additional output at the beginning of the process which is not created by our Javascript code but is somehow injected. Now that should not be a problem because your library ignores all lines until the banner message and the DataReceived event is supposed to be line by line. When I activate all logging for your library I noticed however that when logging the process output both the app insights message and the banner message are contained in a single data event:
![image](https://user-images.githubusercontent.com/2589184/186433194-92515376-4e22-4212-a22f-5c0beb2b7a89.png)

This means that the banner is never recognized by the library (which only checks StartsWith) and therefore is waiting until the timeout for the process even though it's perfectly healthy.

**Comment by JeremyTCD** [comment]
Thanks for the detailed info. We should change it to a regex match then. If you'd like to be a contributor feel free to open a PR. I'll handle the tests etc.

**Comment by aKzenT** [comment]
I will give it a try.

**Comment by JeremyTCD** [comment]
These generate the message:

https://github.com/JeringTech/Javascript.NodeJS/blob/0517756a04fb08df365baa48492a15c23ae9a045/src/NodeJS/Javascript/Servers/OutOfProcess/Http/Http11Server.ts#L52

https://github.com/JeringTech/Javascript.NodeJS/blob/0517756a04fb08df365baa48492a15c23ae9a045/src/NodeJS/Javascript/Servers/OutOfProcess/Http/Http20Server.ts#L38

Jernig.Javascript.NodeJS's "Nullable" dependency needs to be updated to build: `<PackageReference Include="Nullable" Version="1.3.1">`.

Let me know if you have any issues.
