### ISSUE TITLE
Cache control?

### ISSUE THREAD

**Issue by toiyabe** [JeringTech/Javascript.NodeJS#150]
Hello!
When invoking from file, is there a way to prevent caching or limit cache time? This would be very helpful with debugging.
Thanks!
-Eric

**Comment by JeremyTCD** [comment]
Apologies for the very late response,


OutOfProcessNodeJSServiceOptions.ConnectionTimeoutMS

OutOfProcessNodeJSServiceOptions.InvocationTimeoutMS

**Comment by toiyabe** [comment]
Thank you Jeremy!
