### ISSUE TITLE
Is it possible to return a stream from nodejs?

### ISSUE THREAD

**Issue by burner03** [JeringTech/Javascript.NodeJS#159]
Hey there, nice library! It's greatly appreciated.

I've been using it to use React to compile components on the server side and return them as a string

Something like this (simplified): On the server, invoked from InvokeFromStringAsync the JS script:
```
export const render = async (Component) => {
      const componentMarkup = await ReactDOMServer.renderToString(<Component/>);
      return componentMarkup;
} 
```

I saw you were actively responding to questions so maybe you could provide some insight on the possibility of instead of using renderToString here rather use [renderToPipeableStream](https://beta.reactjs.org/reference/react-dom/server/renderToPipeableStream) and return a Stream (instead of "componentMarkup" string) which would be read and output by the server. So far my vague attempts have failed and are returning nothing or empty {}, although no errors are thrown.

**Comment by DaniilSokolyuk** [comment]
Yes it possible , you can use https://github.com/DaniilSokolyuk/NodeReact.NET, 
[renderToPipeableStream](https://beta.reactjs.org/reference/react-dom/server/renderToPipeableStream) is possible in 7.0.3 beta
Here 
https://github.com/DaniilSokolyuk/NodeReact.NET/blob/master/NodeReact/Javascript/interop.js#L100
https://github.com/DaniilSokolyuk/NodeReact.NET/blob/master/NodeReact/Components/ReactBaseComponent.cs#L39

**Comment by burner03** [comment]
Amazing. Thank you!
