### ISSUE TITLE
Which port does this nuget use to communicate with Node.Js ?

### ISSUE THREAD

**Issue by liaosunny123** [JeringTech/Javascript.NodeJS#169]
Which port does this nuget use ?
I have a application which will redirect all the port of the application, that means I need the exactly port that this nuget use and unfilter it to make this lib work normally.  
I find README does not mention it, so I open this issue to ask the port that use, or does the port is random?

**Comment by JeremyTCD** [comment]
Hi, you can configure the Node.js server's port number using [`NodeJSProcessOptions.Port`](https://github.com/JeringTech/Javascript.NodeJS#nodejsprocessoptionsport).

General instructions for configuring options can be found [here](https://github.com/JeringTech/Javascript.NodeJS#configuring).

**Comment by liaosunny123** [comment]
Thanks, it worked!!~
