### ISSUE TITLE
Microsoft.AspNetCore.Hosting.Abstractions is obsolete

### ISSUE THREAD

**Issue by IvanJosipovic** [JeringTech/Javascript.NodeJS#177]
Hi, thanks for this awesome library.

It appears that one of the dependencies is obsolete, see, https://www.nuget.org/packages/Microsoft.AspNetCore.Hosting.Abstractions/
I think this library should be decoupled from asp.net core and a separate package could handle the integration.

**Comment by JeremyTCD** [comment]
Yeah okay, since that package is deprecated it should be removed from the dependencies. 

Will look into it some time next week.

**Comment by JeremyTCD** [comment]
Apologies for the delay, I've published [7.0.0](https://www.nuget.org/packages/Jering.Javascript.NodeJS/7.0.0) with `Microsoft.AspNetCore.Hosting.Abstractions` removed.
