### ISSUE TITLE
Only URLs with a scheme in: file, data, and node are supported by the default ESM loader.

### ISSUE THREAD

**Issue by Michael-Herzog** [JeringTech/Javascript.NodeJS#189]
I get this error when trying to import an external library.

`import { HfInference } from "https://esm.sh/@huggingface/inference"`

**Comment by JeremyTCD** [comment]
Does your script work when you run it directly with node?

**Comment by Michael-Herzog** [comment]
Yes it does. But I also face the problem, that none of NodeJS functions are available when I use your library. But simple script execution works.

**Comment by JeremyTCD** [comment]
It seems network imports are experimental: https://nodejs.org/api/esm.html#https-and-http-imports. You can try specifying the flag using https://github.com/JeringTech/Javascript.NodeJS#nodejsprocessoptionsnodeandv8options.

**Comment by Michael-Herzog** [comment]
Ooh nice :-) This worked. Thanks!
