### ISSUE TITLE
InvocationException: Unexpected reserved word

### ISSUE THREAD

**Issue by Michael-Herzog** [JeringTech/Javascript.NodeJS#190]
I'm trying to implement a simple example from the [HuggingFace JS library](https://huggingface.co/docs/huggingface.js/index).
The code works in simple NodeJS console app I've created with Visual Studio. 

https://huggingface.co/docs/huggingface.js/index

export function test(callback, first, second) {
    const HF_TOKEN = "hf_...";
    const inference = new HfInference(HF_TOKEN);

    await inference.translation({
        model: 't5-base',
        inputs: 'My name is Wolfgang and I live in Amsterdam'
    })
}

But with your library i get this error:

InvocationException: Unexpected reserved word
SyntaxError: Unexpected reserved word
at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:155:18)
at callTranslator (node:internal/modules/esm/loader:285:14)
at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:291:30)
at async link (node:internal/modules/esm/module_job:76:21)

**Comment by JeremyTCD** [comment]
You're using the await keyword in a synchronous method. Not a library issue.

**Comment by Michael-Herzog** [comment]
Stupid me! Sorry for bothering you and thanks for your help!

**Comment by JeremyTCD** [comment]
No prob, good luck with your project!
