### ISSUE TITLE
Support for promises / async-await?

### ISSUE THREAD

**Issue by rjgotten** [JeringTech/Javascript.NodeJS#46]
Would love it if 

https://github.com/JeringTech/Javascript.NodeJS/blob/b0f9166cab73e23d2e0a81f84518d3b91085d46a/src/NodeJS/Javascript/Servers/OutOfProcess/Http/HttpServer.ts#L147

could be amended to take into account a potential `Promise` return value and work with it.
That way modules that hold the RPC function entrypoints can use async/await and forego the callback approach.

Callback-first;error-first is a Node.js convention, but in the face of promises and async/await becoming standardized - also one they very much regret. Would be good to have options.

**Comment by JeremyTCD** [comment]
Good idea. I've added support for async javascript entry methods - #48. Let me know if you have anything to add.

**Comment by rjgotten** [comment]
Oh... using the `AsyncFunction` constructor name; didn't expect that one. Neat idea. Can detect the (a)sync nature of functions 'from the outside' and avoid passing in the callback argument altogether that way.

Technically wouldn't work for a function returning an existing promise, but you can also by contract require that to be wrapped with an async-await. Overhead in computation time there is negligible if you're _already_ awaiting something to complete async.

Nice. 👍

**Comment by JeremyTCD** [comment]
You can explicitly return a promise so long as the method is marked async (included an example in the documentation).  

I've published a new release, 4.4.0, with support for async Javascript functions. Documented [here](https://github.com/JeringTech/Javascript.NodeJS#async-function).  

Thanks for suggesting this, it does make JS entry point code much cleaner :smiley:. Kindly close this issue if you have no other questions.

**Comment by sureshssb07** [comment]
Could you please share the Async/Await or Return Promise sample C# code snippet.  Basically we need to get the return value from promise then() method and assign it in C# variable for proceed further 

Thanks in advance :)

**Comment by JeremyTCD** [comment]
Hi, there are examples in the [docs](https://github.com/JeringTech/Javascript.NodeJS#async-function).

**Comment by sureshssb07** [comment]
We can see the sample with below 

module.exports = {
    doSomething: async (arg1, arg2, arg3, arg4) => {
        ... // Do something with args

        // async functions can explicitly return promises
        return new Promise((resolve, reject) => {
            resolve(result);
        });
    },
    doSomethingElse: async (arg1) => {
        ... // Do something with arg
            
        return result;
    }
}

But Post that how can we bind promise then() in C# side ? or how can we get the async result into C#?

**Comment by JeremyTCD** [comment]
You can also find information on invoking from C# in the [docs](https://github.com/JeringTech/Javascript.NodeJS#invoking-javascript-in-string-form).
