### ISSUE TITLE
Installing via NuGet in VS2019 with AspNetCore 2.1

### ISSUE THREAD

**Issue by johnnyoshika** [JeringTech/Javascript.NodeJS#50]
There is a version conflict with AspNetCore.Hosting.Abstractions when trying to install NodeJS with the following combination:
* Visual Studio 2019
* AspNetCore 2.1.0

Visual Studio 2019 error message:
![image](https://user-images.githubusercontent.com/504505/69164165-54b0ab00-0aa4-11ea-9d5e-c2f5c87412f8.png)

Here is the content of my csprog file:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>

```

Here is the content of my global.json file:

```
{
  "sdk": {
    "version": "2.1.300"
  }
}
```

Note: I don't experience any of these problems once I upgrade to .Net Core 3.

**Comment by JeremyTCD** [comment]
Thanks for the details. This issue has to do with `Microsoft.AspNetCore.App`'s strict version requirements, from [Microsoft.AspNetCore.App for ASP.NET Core](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/metapackage-app.md):

> - Other packages added to your app cannot change the version of packages included in Microsoft.AspNetCore.App.
> - Version consistency ensures a reliable experience. Microsoft.AspNetCore.App was designed to prevent untested version combinations of related bits being used together in the same app.

For the same reason, both `Microsoft.AspNetCore.NodeServices` v2.2.0 and v3.0.0 can't be installed in your example AspNetCore project.  

Is it possible for you to upgrade your projects to dotnetcore2.2+? If it isn't we could look into this further.

**Comment by johnnyoshika** [comment]
@JeremyTCD This isn't a problem for me at all. I upgraded to .Net Core 3 and everything immediately worked. I created this issue because you asked me to. :-) Would you like me to close this issue?

**Comment by JeremyTCD** [comment]
Haha I see. I'll close it since it's mostly a `Microsoft.AspNetCore.App` issue. Feel free to open another issue if you run into problems again.  

For anyone who encounters this issue, you can either:
- Bump your target framework version.
- Use an older Jering.Javascript.NodeJS version.
