### ISSUE TITLE
InvokeFromStringAsync cannot load modules from node_modules

### ISSUE THREAD

**Issue by austinw-fineart** [JeringTech/Javascript.NodeJS#58]
https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders
InvokeFromFileAsync works perfectly fine if you try to load modules like this: `require('jsdom')`, so long as it follows the rules above. Since there is no script file when using InvokeFromStringAsync, you would think that require starts from NodeJS's working directory, like it does when running the cli. However, setting NodeJSProcessOptions.ProjectPath does not appear to have any effect and module.paths is undefined as well.

**Comment by JeremyTCD** [comment]
Thanks for reporting this!  

Just to be clear, you meant "`InvokeFromStringAsync` cannot load modules from node_modules" right?

Anyway you were right, there is an issue. I've fixed it (#59), planning to write a few more tests, new version with fix will be out by tomorrow.

**Comment by JeremyTCD** [comment]
I've published a new release, 5.1.1, with the fix. Kindly update this issue's title and close it if the fix solves your issue.

**Comment by austinw-fineart** [comment]
Ah that's my bad. I can confirm the bug is fixed with 5.1.1
