### ISSUE TITLE
Modifiable objects passed to scripts?

### ISSUE THREAD

**Issue by RickBullotta** [JeringTech/Javascript.NodeJS#66]
I'm assuming that since execution is out-of-process, there's no way to pass back modified values for arguments to a script.  I've experimented with both simple types and with collections and neither allowed this.  No real issue, just wanted to clarify that this was the case.

Also, I've been passing a Dictionary<string,object> instance to scripts to represent the equivalent of a JSON object, and it just magically "works".  Nice job!  Is that the optimal approach to use?

**Comment by DaniilSokolyuk** [comment]
@RickBullotta Hi! No magic here, your models is serialized by [System.Text.Json](https://github.com/JeringTech/Javascript.NodeJS/blob/master/src/NodeJS/Utils/JsonService.cs) and passed to node.js as string, then on response value is deserialized. Dictionary<string,object> should work on serialize, but on deserializing you can have some problems, because System.Text.Json doesnt support object deserialization, you can register your own IJsonService implementation with [this](https://github.com/dotnet/runtime/blob/3cec4f50af9fc68bcde80952427092f7a8873864/src/libraries/System.Text.Json/tests/Serialization/CustomConverterTests.Object.cs#L267) converter for example.

**Comment by RickBullotta** [comment]
Actually deserialization/returning JSON objects seems to work fine.  I have successfully returned complex JSON objects with no problem, and no custom converter needed.  The returned type I'm getting is JsonElement.

**Comment by JeremyTCD** [comment]
Hi @RickBullotta, @DaniilSokolyuk's explanation is excellent, just thought I'd add some comments:

> I'm assuming that since execution is out-of-process, there's no way to pass back modified values for arguments to a script.

You can modify an argument and pass back the result:

```csharp
public class Data
{
    public string Message { get; set; }
}
```

```csharp
const string module = @"module.exports = (callback, data) => {
    data.message += '!';
    callback(null, data);
}";

var data = new Data { Message = "Hello" };

Data result = await StaticNodeJSService.InvokeFromStringAsync<Data>(module, args: new object[] { data }).ConfigureAwait(false);

// We've added an exclamation mark to our message!
Assert.Equal("Hello!", result.Message);
```

> Also, I've been passing a Dictionary<string,object> instance to scripts to represent the equivalent of a JSON object, and it just magically "works". Nice job! Is that the optimal approach to use?

This is a perfectly valid way to use the library. @DaniilSokolyuk has a point about being careful with the `object` type though:

```csharp
const string module = @"module.exports = (callback) => {
    callback(null, 1); // Pass back 1
}";

// object as return type
object result = await StaticNodeJSService.InvokeFromStringAsync<object>(module, args: new object[] { data }).ConfigureAwait(false);

// Throws Assert.Equal() Failure
// Expected: 1 (System.Int32)
// Actual: 1 (System.Text.Json.JsonElement)
Assert.Equal(1, result);
```

`System.Text.Json` doesn't infer types when deserializing. So for example, if it sees a `1` and the return type is `object`, it doesn't cast to `Int32`, it just returns a`JsonElement`. This is fine if you aren't going to perform mathematical operations on the returned value.  

----- 

Do let us know if you have any other questions!

**Comment by RickBullotta** [comment]
Yup.  Makes sense.  But I guess you're limited to one parameter in the callback?

**Comment by JeremyTCD** [comment]
@RickBullotta Yeap only one, though as you mentioned you can pack values, I'd create a model or use an array. Feel free to close this issue if we've clarified things for you.
