### ISSUE TITLE
Add support for WatchFileExtensions

### ISSUE THREAD

**Issue by flcdrg** [JeringTech/Javascript.NodeJS#67]
As mentioned in https://github.com/dotnet/aspnetcore/issues/12890#issuecomment-554814873, one difference is the lack of support for the equivalent of `NodeServicesOptions.WatchFileExtensions`

We make use of that feature in NodeServices and would like to see something similar added here

**Comment by JeremyTCD** [comment]
Hi @flcdrg, if it's not too much to ask, would you mind sharing your use case for `WatchFileExtensions`? How often do your files change?

The way `Microsoft.AspNetCore.NodeServices` implements it, the entire Node process gets restarted every time a file changes. Using NodeJS's [fs module](https://nodejs.org/docs/latest/api/fs.html) to watch for file changes from your NodeJS script is quite a lot more efficient.

**Comment by DaniilSokolyuk** [comment]
In my library based on Javascript.NodeJS, i am too using fs module, https://github.com/DaniilSokolyuk/NodeReact.NET/blob/7914beafb5df0f3241b266ed484c849e411d2781/NodeReact/Javascript/interop.js#L23

**Comment by flcdrg** [comment]
We're investigating the `fs` module option. Not sure if will work in our scenario or not. Will get back to you shortly.

**Comment by JeremyTCD** [comment]
Sure, let us know.

**Comment by rosslovas** [comment]
We were able to add the following to our entry point to achieve essentially the same effect. It seems like it'll suit our use case, which is simply allowing us to update the part of our application that changes the most frequently (after config files), the js that accommodate per-client tweaks, with minimal downtime. (Also, it's very handy during development!)

```ts
fs.watch(__dirname, { recursive: true }, (eventType, filename) => {
    if (['.js', '.json', ...].includes(path.extname(filename))) {
        console.log(`File changed, killing Node.JS process: ${filename}`);
        process.exit(0);
    }
});
```

There are some caveats: `recursive` option doesn't work on Linux, if you have multiple entry points you need to make sure this runs in each (but only once per engine), and it assumes this library will always continue to cleanly handle `node` unexpectedly exiting, restarting it when it's next needed without error.

**Comment by JeremyTCD** [comment]
File watching seems like a popular feature. I've created a proposal for file watching based on @rosslovas's code: https://github.com/JeringTech/Javascript.NodeJS/pull/69. Feedback/help appreciated - would the addition be sufficient for your use cases?  

Bit busy this week, will flesh it out this coming weekend.

**Comment by JeremyTCD** [comment]
File watching is now supported - [5.4.0](https://www.nuget.org/packages/Jering.Javascript.NodeJS/5.4.0).  

Big thanks to everyone who contributed tips and ideas.

## Enabling file watching:
``` csharp
services.Configure<OutOfProcessNodeJSOptions>(options => options.EnableFileWatching = true);
```
 ([More info on configuring options](https://github.com/JeringTech/Javascript.NodeJS#configuring-inodejsservice))

## Options

[OutOfProcessNodeJSOptions](https://github.com/JeringTech/Javascript.NodeJS#outofprocessnodejsserviceoptions) 

- WatchPath
- WatchSubdirectories
- WatchFileNamePatterns
- WatchGracefulShutdown

## Benchmarks
- [NodeJS restart duration](https://github.com/JeringTech/Javascript.NodeJS#file-watching)
- [Effect on latency](https://github.com/JeringTech/Javascript.NodeJS#latency) (INodeJSService_Latency_InvokeFromFile_GracefulShutdownEnabled)
