### ISSUE TITLE
Example of returning a stream? Result.stream is undefined

### ISSUE THREAD

**Issue by Edza** [JeringTech/Javascript.NodeJS#72]
I'm new to node.js streams, buffers and pipes.

I have a buffer that deserializes to:
`{"type":"Buffer","data":[49,46,48,48,49,58,49,49,51,29,49,46,48,48,50,58,48,53,48,50,29,49,46,48,48,51,58,49,31,49,30,50,31,48,48,29,49,46,48,48,52
`

I would like to return it as a stream.

For example I have this index.js:
`module.exports = function(result, ...`

To return a stream I would have to do something like:

```
        var stream = require('stream');
        var bufferStream = new stream.PassThrough();
        bufferStream.end(f(message));
        bufferStream.pipe(result.stream)
```

This is my calling code:
```
 dynamic result2 = StaticNodeJSService
.InvokeFromFileAsync<Stream>(
@"...\index.js",
args: new[] { "..." }).Result;
```

**however result.stream seems to be undefined**, and I get an error:
```
'One or more errors occurred. (Cannot read property 'on' of undefined
TypeError: Cannot read property 'on' of undefined
    at PassThrough.Readable.pipe (_stream_readable.js:612:8)

```

**What am I doing wrong? Why is result.stream null?**

**Comment by Edza** [comment]
Calling:
result(null, bufferStream); - does not throw an error, but still does not work, stream is empty

**Comment by Edza** [comment]
It does return with <dynamic> a string.

**Comment by JeremyTCD** [comment]
Hi there, the code has several issues:

- The function you assigned to `module.exports` must take a callback as its
first argument. At the end of the function, you must call the callback. Its
first parameter must be an error object (or null if you don't encounter any
errors). Its second parameter should be your stream. You do not need to
pipe your stream. Refer to
https://github.com/JeringTech/Javascript.NodeJS/blob/master/ReadMe.md#basics
for instructions on how to write your function.

- To get a `Stream` back in .Net, You've got to call `Stream result2 =
StaticNodeJSService
.InvokeFromFileAsync<Stream>(...`.

Let me know if you encounter any other issues.
I'm not at my computer right now so I can't put a full example together
right now.

**Comment by JeremyTCD** [comment]
Turns out there was a bug with returning `Stream` (https://github.com/JeringTech/Javascript.NodeJS/pull/73). Thanks a lot for reporting this issue!  

I've fixed it and released [5.3.2](https://www.nuget.org/packages/Jering.Javascript.NodeJS/5.3.2).  

There was indeed a lack of tests/examples for the `Stream` return value use case. I've added a test/example:

https://github.com/JeringTech/Javascript.NodeJS/blob/1e7e55c1d152ca3b8ef5a2152877edcc2bdebac4/test/NodeJS/HttpNodeJSServiceIntegrationTests.cs#L989-L1008

If this solves your problem kindly close this issue.

**Comment by Edza** [comment]
Ok, will test today, thanks.

**Comment by Edza** [comment]
Yeah! Works. Thanks a lot. Can close. :D

**Comment by Edza** [comment]
I do have a quick question, tho. I also want to get the opposite direction to work.

Pass a byte[] back to node.js.

Looks like some people do it by converting to hex and then to binary in node:
https://stackoverflow.com/questions/45571137/unable-to-pass-stream-as-parameter-to-js-in-aspnet-core-nodeservices

What approach would you recommend for passing a byte[] to node.js?

**Comment by Edza** [comment]
I managed to get it work using the HEX example.

**Comment by JeremyTCD** [comment]
@Edza glad it works for you!  

About `byte[]`s, they're automatically serialized to base64 strings (Jering.Javascript.NodeJS uses System.Text.Json, which does this by default).  

This means you can pass the `byte[]` directly to your invoke method. You can then create a buffer from the base64 string in your NodeJS script:

``` csharp
// Arrange
const string module = @"module.exports = (callback, data) => {
    let buffer = new Buffer(data, 'base64');
    callback(null, buffer[0] + buffer[1] + buffer[2] + buffer[3]);
}";
var data = new byte[] { 1, 2, 3, 4 };
HttpNodeJSService testSubject = CreateHttpNodeJSService();

// Act
int result = await testSubject.InvokeFromStringAsync<int>(module, args: new[] { data }).ConfigureAwait(false);

// Assert
Assert.Equal(1 + 2 + 3 + 4, result);
```

Feel free to open a new issue if you encounter any other problems.
