### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by dustinsoftware** [JeringTech/Javascript.NodeJS#75]
It would be awesome to have first-class support for automating Node instances on Linux. Just like Windows, Node would already need to be installed on the environment.

Use case:
- Deploy as a part of a .NET core app in a Docker container
- Much less overhead and cost to manage a Linux instance on Digital Ocean / AWS
- Allows supporting ARM targets, for instance, Raspberry PI.

Challenges:
- Entirely different process model, spawning & cleaning up Node instances will have platform-specific quirks
- Different path structure consider when resolving modules

https://github.com/reactjs/React.NET/ currently supports Windows, OS X, and Linux as distribution targets via JSEngineSwitcher.ChakraCore by shipping binary blobs of the ChakraCore runtime, resolved at runtime. This only works on x64 platforms, however.

**Comment by JeremyTCD** [comment]
Hey! Not sure if I get you right, this library does work on Linux and OS X - all pull requests are built and tested on Linux, OS X and Windows. Am personally using this library in a project running on Ubuntu.  

Will look into verifying that it works in the other scenarios you mentioned:

> - Deploy as a part of a .NET core app in a Docker container
> - Allows supporting ARM targets, for instance, Raspberry PI.

Architecture-wise, there aren't any limitations, the library works on any machine with a Node.js executable: arm x32 and x64, intel x32 and x64 should all be fine.

As an aside, I'm working on shipping Node.js binaries in a Nuget package, so users don't need to install Node.js. This should provide your users with a similar experience to using ChakraCore.

**Comment by dustinsoftware** [comment]
You know what, I think I was misled by the documentation... will send a PR so it doesn't confuse others. (I didn't bother trying since it looked like it was Windows only)
