### ISSUE TITLE
Deep argument serialization

### ISSUE THREAD

**Issue by Edza** [JeringTech/Javascript.NodeJS#79]
Hi,

Trying to pass arguments inside:
module.exports = (callback, arg1, arg2, arg3)

I have an object, let's say Person. Who has a List<Adress> and Adress has fields StreetName and City.

Currently it looks like:
class Person {
 string Name; // is serialized
 List<Adress>... // is not serialized

}

Also if I pass a List<Adress> as an argument inside arg2 for example, I do not have access to AddressInList.StreetName - undefined.

Looks like arg1, arg2, arg3 does shallow serialization when sending to node script. Is this correct?

**Comment by Edza** [comment]
More basic question - is passing a List<> with objects that have fields possible in argument list?

**Comment by JeremyTCD** [comment]
Hi again! Serialization is done using [`System.Text.Json.JsonSerializer`](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer?view=netcore-3.1):

https://github.com/JeringTech/Javascript.NodeJS/blob/fbc638e077b5e6dc37e3797396d7ec37c2543c7b/src/NodeJS/Utils/JsonService.cs#L31-L34

Default options: 

https://github.com/JeringTech/Javascript.NodeJS/blob/fbc638e077b5e6dc37e3797396d7ec37c2543c7b/src/NodeJS/Utils/JsonService.cs#L14-L22

So technically, it *should* serialize your list and its contained elements (primitive or not). I'll run some tests when I have time tomorrow.

**Comment by JeremyTCD** [comment]
Deep serialization works fine, the following console application prints the expected output:

```csharp
class Program
{
    static void Main(string[] args)
    {
        var people = new List<Person> {
            new Person("name1", new List<Address>{ new Address("streetName1", "city1") }),
            new Person("name2", new List<Address>{ new Address("streetName2", "city2") })
        };
        const string dummyModule = @"module.exports = (callback, people) => {{
var result = '';

for(var i = 0; i < people.length; i++) {
    var person = people[i];
    var address = person.addresses[0];

    result += `${person.name} ${address.streetName} ${address.city}\n`;
}

callback(null, result);
}}";

        string result = StaticNodeJSService.InvokeFromStringAsync<string>(dummyModule, args: new object[] { people }).GetAwaiter().GetResult();

        // Prints:
        // name1 streetName1 city1
        // name2 streetName2 city2
        Console.WriteLine(result);
    }

    private class Person
    {
        public Person(string name, List<Address> addresses)
        {
            Name = name;
            Addresses = addresses;
        }

        public string Name { get; set; }
        public List<Address> Addresses { get; set; }
    }

    private class Address
    {
        public Address(string streetName, string city)
        {
            StreetName = streetName;
            City = city;
        }

        public string StreetName { get; set; }
        public string City { get; set; }
    }
}
```

I suggest double checking your js. Note that js properties are camel-cased, i.e. `streetName`, not `StreetName`.

**Comment by Edza** [comment]
I'm not able to get it to work. :(

**Comment by Edza** [comment]
Maybe I should add the [Serializable] attribute?

**Comment by Edza** [comment]
Alright, thanks. I'll try to change the cases. A bit confused about that.

I have a field ALLCAPS, does it get converted to allcaps as well?

**Comment by Edza** [comment]
It worked. Thanks 👍

**Comment by JeremyTCD** [comment]
> I have a field ALLCAPS, does it get converted to allcaps as well?

Interesting question, I don't know to be honest. Perhaps write up a test or check out the `System.Text.Json` documentation.  

Anyway glad it works. Feel free to open another issue if you encounter more problems or have any questions!

**Comment by runxc1** [comment]
How do you change the Naming policy that is currently the default?   I have some existing code that is used as a javascript template or sorts so there are hundreds of templates that require the names of properties to not be changed which seems to be the current default.  Is there a way to over ride the defaults?

**Comment by JeremyTCD** [comment]
Hey! The library uses vanilla dependency injection (DI) for extensibility, see [Microsoft's dependency injection documentation](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection) for info on DI.   

You can [overwrite](https://github.com/JeringTech/Javascript.NodeJS#extensibility) the default implementation of `IJsonService` using standard DI patterns.  

First, implement your own `IJsonService`. This is the default implementation:

```cs
/// <summary>
/// The default implementation of <see cref="IJsonService"/>.
/// </summary>
public class JsonService : IJsonService
{
    private static readonly JsonSerializerOptions _jsonSerializerOptions = new JsonSerializerOptions
    {
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,

        // ***** Specify your naming policy *****
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        IgnoreNullValues = true,

        PropertyNameCaseInsensitive = true
    };

    /// <inheritdoc />
    public ValueTask<T> DeserializeAsync<T>(Stream stream, CancellationToken cancellationToken = default)
    {
        return JsonSerializer.DeserializeAsync<T>(stream, _jsonSerializerOptions, cancellationToken);
    }

    /// <inheritdoc />
    public Task SerializeAsync<T>(Stream stream, T value, CancellationToken cancellationToken = default)
    {
        return JsonSerializer.SerializeAsync(stream, value, _jsonSerializerOptions, cancellationToken);
    }
}
```

Then register it:

```cs
var services = new ServiceCollection();
services.AddNodeJS();

// Overwrite the default DI service
services.AddSingleton<IJsonService, MyJsonService>();

ServiceProvider serviceProvider = services.BuildServiceProvider();
INodeJSService nodeJSService = serviceProvider.GetRequiredService<INodeJSService>();
```

If you're using the static API, you can register your custom `IJsonService` like this:

```

StaticNodeJSService.SetServices()
```

**Comment by runxc1** [comment]
Awesome thanks for this, just what I was looking for.
