### ISSUE TITLE
Question about concurrency of multiple independent caller processes

### ISSUE THREAD

**Issue by Edza** [JeringTech/Javascript.NodeJS#81]
Hi,

I have a build server which runs many builds at the same time. Part of the build is running tests. One of the tests is an integration test that calls node.js using this library.

Let's say I have 4 instances of this test running from 4 different calling processes (MSBUILD), is the node.js listener server script written in a way, that it support multiple instances of it co-existing?

**Comment by JeremyTCD** [comment]
Hi again! Yes absolutely. Each `INodeJSService` starts each own Node.js process and only communicates with it. Whether they're in the same process or in several, `INodeJSService`s will not interfere with each other. Are you having issues with your tests?

**Comment by Edza** [comment]
Nope, no issues. Just checking, to make sure it will work fine. :D You can close this, thanks.

**Comment by JeremyTCD** [comment]
Haha okay sure!
