### ISSUE TITLE
Question: Example to replace aspnet-prerendering in asp.net core 3.1?

### ISSUE THREAD

**Issue by christopherpross** [JeringTech/Javascript.NodeJS#82]
Hey,
I hope this is the right place.
At the moment, I try to reach ssr with angular under asp.net core 3.1 and want to use your library. Is there a good exaple? Have I replace many code or have I only write some lines?
I don't know how to do that, so maybe someone can point me in the right direction?

all the best,
Christopher

**Comment by JeremyTCD** [comment]
Hey! This library doesn't do server side rendering. I believe what you need is [Microsoft.AspNetCore.SpaServices.Extensions](https://www.nuget.org/packages/Microsoft.AspNetCore.SpaServices.Extensions). [This thread](https://github.com/dotnet/aspnetcore/issues/12890#issue-477050062) provides more information.

**Comment by christopherpross** [comment]
hm, ok. The nuget packet you have liked, I already know. But there is no documentation out there. In an answer in this anouncment, some guy has recomented for ssr with angular and so on your library. But sorry, if this information was wrong. I close this now. If there is potencial for go foder in this, it can reopened.
