### ISSUE TITLE
Issue running with node 13/14 

### ISSUE THREAD

**Issue by giuliano-barberi-tf** [JeringTech/Javascript.NodeJS#89]
It appears there are issues running on newer versions of node 13 and 14. I have gotten it to work with node 13.8.0 but it fails on 13.14.0 or latest node 14.

I get this error whenever I try to run it inside of a docker container:

```
node[64]: ../src/node_http_parser.cc:523:static void node::{anonymous}::Parser::Initialize(const v8::FunctionCallbackInfo<v8::Value>&): 
Assertion `args[4]->IsInt32()' failed.
 1: 0xa0e670 node::Abort() [node]
 2: 0xa0e6ee  [node]
 3: 0xa2447a  [node]
 4: 0xbf0cec  [node]
 5: 0xbf2af7 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
 6: 0x13da5f9  [node]
```

It appears to error out on this line: https://github.com/nodejs/node/blob/v13.14.0/src/node_http_parser.cc#L523
```
    if (args.Length() > 4) {
      CHECK(args[4]->IsInt32());
      headers_timeout = args[4].As<Number>()->Value();
    }
``` 

so it looks related to the header timeout perhaps? Maybe the number being set in HttpServer.ts is too large and not a valid int32?

**Comment by JeremyTCD** [comment]
Hey thanks for the detailed report! Was able to reproduce the issue with 13.8.0. The problem was indeed header timeout being too large, limiting it to max int 32 fixed the issue.  

A separate test started failing with 13.8.0, will resolve that then publish Jering.Javascript.Nodejs 5.4.3 with fixes for both issues.

**Comment by JeremyTCD** [comment]
🚀 [5.4.3](https://www.nuget.org/packages/Jering.Javascript.NodeJS/5.4.3) released. Thanks again for reporting the issue!

**Comment by giuliano-barberi-tf** [comment]
> 🚀 [5.4.3](https://www.nuget.org/packages/Jering.Javascript.NodeJS/5.4.3) released. Thanks again for reporting the issue!

Thanks for the quick fix
