### ISSUE TITLE
Received a HTTP response with an unexpected status code: ServiceUnavailable

### ISSUE THREAD

**Issue by villelaitila** [JeringTech/Javascript.NodeJS#91]
There is a problem when trying to take into use:
```
{
  "exceptionType": "InvocationException",
  "message": "Received a HTTP response with an unexpected status code: ServiceUnavailable.",
  "stackTrace": "   at Jering.Javascript.NodeJS.HttpNodeJSService.TryInvokeAsync[T](InvocationRequest invocationRequest, CancellationToken cancellationToken)",
  "failingDependencyUri": null
}
```

when using example code
```
string javascriptModule = @"
module.exports = (callback, x, y) => {  // Module must export a function that takes a callback as its first parameter
    var result = x + y; // Your javascript logic
    callback(null /* If an error occurred, provide an error object or message */, result); // Call the callback when you're done.
}";
```

**Comment by JeremyTCD** [comment]
Hi! I've just manually double checked the latest Jering.Javascript.NodeJS release, couldn't reproduce your error.  

Am happy to help resolve the issue though.  To begin with, could you provide these details:  

- Is this an intermittent (occurs randomly) or systematic (occurs every time you invoke) error?
- Operating system
- Version of Node.js installed on your machine

**Comment by JeremyTCD** [comment]
Closed due to inactivity. Feel free to open a new issue if you have any issues!

**Comment by ynchui** [comment]
We are facing the same issue:

It is intermitent
Windows OS
16.20.0

**Comment by ynchui** [comment]
> Closed due to inactivity. Feel free to open a new issue if you have any issues!

We are facing the same issue:

It is intermitent
Windows OS
16.20.0
