### ISSUE TITLE
Error: Cannot find module 'xmldom'

### ISSUE THREAD

**Issue by jefersonmlopes** [JeringTech/Javascript.NodeJS#94]
Hi

I'm having problems using the InvokeFromFileAsync method when my js file uses the dependency of other modules, below the settings and details of my implementation.

**Index.js**
```js
module.exports = (callback, gpxString) => {  // Module must export a function that takes a callback as its first parameter

    const tj = require("@tmcw/togeojson");
    // node doesn't have xml parsing or a dom. use xmldom
    const DOMParser = require("xmldom").DOMParser;
    const gpx = new DOMParser().parseFromString(gpxString);
    const converted = tj.gpx(gpx);

    //    const convertedWithStyles = tj.kml(kml, { styles: true });

    var result = converted; // Your javascript logic

    callback(null /* If an error occurred, provide an error object or message */, result); // Call the callback when you're done.
}
```

**.net project configuration:**
```c#
public class NodeJSDepedencies : IDependencyGroup
    {
        public void Register(ILogger logger, IServiceCollection services)
        {
            services.AddNodeJS();

            ServiceProvider serviceProvider = services.BuildServiceProvider();
            // Options for the NodeJSProcess, here we enable debugging
            services.Configure<NodeJSProcessOptions>(options =>
            {
                options.NodeAndV8Options = "--inspect-brk";
                options.ProjectPath = @"C:\PersonalWorkspace\ConvertGPXToGeoJson\src";
            });

            // Options for the service that manages the process, here we make its timeout infinite
            services.Configure<OutOfProcessNodeJSServiceOptions>(options => options.TimeoutMS = -1);


            INodeJSService nodeJSService = serviceProvider.GetRequiredService<INodeJSService>();
            services.TryAddSingleton<INodeJSService>(serviceProvider.GetRequiredService<INodeJSService>());
        }
    }
```

**Call InvokeFromFileAsync:**

```c#
var result2 = await _nodeJSService.InvokeFromFileAsync<dynamic>("index.js", args: new[] { text });
```

**Error:** 
`Cannot find module 'xmldom'\nRequire stack:\n- C:\\PersonalWorkspace\\ConvertGPXToGeoJson\\src\\index.js\n- C:\\PersonalWorkspace\\ConvertGPXToGeoJson\\src\\[eval]\r\nError: Cannot find module 'xmldom'\nRequire stack:\n- C:\\PersonalWorkspace\\ConvertGPXToGeoJson\\src\\index.js\n- C:\\PersonalWorkspace\\ConvertGPXToGeoJson\\src\\[eval]\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:725:27)\n    at Module.require (internal/modules/cjs/loader.js:952:19)\n    at require (internal/modules/cjs/helpers.js:88:18)\n    at module.exports (C:\\PersonalWorkspace\\ConvertGPXToGeoJson\\src\\index.js:6:23)\n    at Server.<anonymous> ([eval]:1:4360)\n    at Generator.next (<anonymous>)\n    at [eval]:1:1271\n    at new Promise (<anonymous>)\n    at r ([eval]:1:1016)`

**Comment by JeremyTCD** [comment]
Hi! I can't reproduce the issue. [Minimal repro](https://github.com/JeremyTCD/Test.NodeJS.Modules):

```cs
class Program
{
    static async Task Main()
    {
        // Register service
        var services = new ServiceCollection();

        services.AddNodeJS();
        ServiceProvider serviceProvider = services.BuildServiceProvider();

        // Get service
        INodeJSService nodeJSService = serviceProvider.GetRequiredService<INodeJSService>();

        // Invoke js
        string dummyXml = @"<xml xmlns=""a"" xmlns:c=""./lite""></xml>";
        string result = await nodeJSService.InvokeFromFileAsync<string>("index.js", args: new[] { dummyXml });
        Console.Write(result);
    }
}
```

```js
module.exports = (callback, dummyXml) => {
    const DOMParser = require('xmldom').DOMParser;
    const doc = new DOMParser().parseFromString(dummyXml, 'text/xml');

    // Add attribute to dummy XML
    doc.documentElement.setAttribute('x', 'y')

    callback(null, doc.toString());
}
```

 To try the repro:

- Clone it
- In the project root, run `yarn install`
- Run the console application in VS

It should print `<xml xmlns="a" xmlns:c="./lite" x="y"/>`.   

The issue is likely with project structure. Would appreciate if you could see where our projects differ and troubleshoot based on that. If the issue persists create a minimal repro and push to Github. Would be happy to take a look at it.

**Comment by JeremyTCD** [comment]
Closed due to inactivity. Feel free to reopen if you have any other questions.
