### ISSUE TITLE
Sending parameters

### ISSUE THREAD

**Issue by markzolotoy** [JeringTech/Javascript.NodeJS#95]
This is not an issue, but a question.
How can I send parameters to module.exports?
I have this: 
module.exports = (callback, exportSettings) in ts file and this in c#:
image = await StaticNodeJSService.InvokeFromFileAsync<string>("test_nodejs_script.js",
                   args: new [] { exportSettings });
I am not sure the ts file gets exportSettings string.
Also how can I have a breakpoint in ts file?

Thanks

**Comment by JeremyTCD** [comment]
Hey! Your argument passing looks fine to me. You'll need to specify a return type though.

Your C#:
```cs
var image = await StaticNodeJSService.InvokeFromFileAsync("test_nodejs_script.js", args: new [] { exportSettings });
```

Expected C#:
```cs
var image = await StaticNodeJSService.InvokeFromFileAsync<your return type here>("test_nodejs_script.js", args: new [] { exportSettings });
```

Your return type must be a JSON-serializable type, `string`, or `Stream`.

As for debugging: [instructions](https://github.com/JeringTech/Javascript.NodeJS#debugging-javascript), example [options](https://github.com/JeringTech/Javascript.NodeJS#configuring-inodejsservice).  

Let me know if you need further help.

**Comment by markzolotoy** [comment]
Thanks for your help. I still cannot get debugging going. I added debugger statement to my JS code. I also have Nodejs console open, but it's not getting into debugging.

**Comment by JeremyTCD** [comment]
I've created an [example project](https://github.com/JeremyTCD/Test.NodeJS.Debugging):

- Clone and run
- Navigate to chrome://inspect/ in Chrome and chrome://inspect/ in Chrome
- Click "Open dedicated DevTools for Node" and wait for the debugger to attach

**Comment by markzolotoy** [comment]
It worked just once, after that is not attaching to the Browser no matter what.

**Comment by markzolotoy** [comment]
In Edge I am getting into this:
![image](https://user-images.githubusercontent.com/7363944/106491750-ce03a600-647c-11eb-994d-4aeff19469c5.png)

**Comment by markzolotoy** [comment]
When I run it in the VS2019 I get command window open which says:
C:\Test.NodeJS.Debugging-main\bin\Debug\netcoreapp3.1\Test.NodeJS.Debugging.exe (process 4156) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .

**Comment by markzolotoy** [comment]
I cleaned up a little and command window opens blank, but still no debugging.

**Comment by markzolotoy** [comment]
After killing the running process once the next run will have:
C:\Test.NodeJS.Debugging-main\bin\Debug\netcoreapp3.1\Test.NodeJS.Debugging.exe (process 4156) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .

**Comment by JeremyTCD** [comment]
The example project works on my machine. Unfortunately this looks like a machine-specific issue. Closing for now, feel free to open a new issue if you have questions.
