### ISSUE TITLE
Relative path for InvokeFromFileAsync

### ISSUE THREAD

**Issue by markzolotoy** [JeringTech/Javascript.NodeJS#98]
I am trying to have a relative path to my script file. I have a subfolder "NodeScripts" in a web folder that the app is running from. The script file is inside of NodeScripts. The command looks like this:
StaticNodeJSService.InvokeFromFileAsync<string>("./NodeScripts/exportChart.js"

does not work. If I specify a full local path then it works.
Any idea?

Thanks

**Comment by JeremyTCD** [comment]
Hey! Sorry I lost track of your debugging issue. Did you manage to resolve it?  

As for relative paths, they're resolved relative to [`ProjectPath`](https://github.com/JeringTech/Javascript.NodeJS#nodejsprocessoptions). Setting it with the static API:

```cs
var services = new ServiceCollection();

services.AddNodeJS();
services.Configure<NodeJSProcessOptions>(options => options.ProjectPath = <your root path here>);
StaticNodeJSService.SetServices(services);

StaticNodeJSService.InvokeFromFileAsync("./NodeScripts/exportChart.js");
```

Alternatively,  you can have MSBuild copy your scripts to a directory in `bin`. This way you'll likely have your scripts in a fixed location relative to the default `ProjectPath`. Default `ProjectPath` is what `Directory.GetCurrentDirectory()` returns in your application.

**Comment by markzolotoy** [comment]
No, the debugging is still not working.

**Comment by markzolotoy** [comment]
But <your root path here> is still a hard coded local path?

**Comment by JeremyTCD** [comment]
Yeap, try the alternative:

> Alternatively, you can have MSBuild copy your scripts to a directory in bin. This way you'll likely have your scripts in a fixed location relative to the default ProjectPath. Default ProjectPath is what Directory.GetCurrentDirectory() returns in your application.

**Comment by markzolotoy** [comment]
Here is what I did:
services.Configure<NodeJSProcessOptions>(options => options.ProjectPath =
AppDomain.CurrentDomain.BaseDirectory);
Works fine with:
StaticNodeJSService.InvokeFromFileAsync<string>("./NodeScripts/exportChart.js",

**Comment by JeremyTCD** [comment]
Thanks for sharing. Seems like `AppDomain.CurrentDomain.BaseDirectory` might be a better default than `GetCurrentDirectory` since it generally points to the directory with your entry dll. Will consider that for 6.0.0 of this library.  

Feel free to open another issue if you have more questions!
