### ISSUE TITLE
Failed to connect to NodeJS. Refer to the inner exception for details.

### ISSUE THREAD

**Issue by markzolotoy** [JeringTech/Javascript.NodeJS#99]
I am getting this error. I have everything working fine on my local box. I have installed the app on the VM using TFS build. I am assuming that all the needed libs were included. Any idea what might be wrong?

Thanks

**Comment by JeremyTCD** [comment]
First thing is to make sure Node is installed and added to the `path` environment variable. 

Try `node --version` in a console on your VM to verify that.  

If the issue persists, log the inner exception and we'll troubleshoot from there.

**Comment by markzolotoy** [comment]
Yes, I figured. After installing nodejs and restarting to box  the problem went away.

**Comment by JeremyTCD** [comment]
Glad its working! Feel free to open another issue if you have any other questions.
